name: ADF CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: ğŸ“¦ Install ADF Utility
        run: npm install @microsoft/azure-data-factory-utilities

      - name: âœ… Validate ADF code
        run: |
          node node_modules/@microsoft/azure-data-factory-utilities/lib/index validate ./data-factory/ "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.ADF_DEV_RG }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_DEV_NAME }}"

      - name: ğŸ“¤ Export ARM Template
        run: |
          mkdir -p arm-output
          node node_modules/@microsoft/azure-data-factory-utilities/lib/index export ./data-factory/ "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.ADF_DEV_RG }}/providers/Microsoft.DataFactory/factories/${{ secrets.ADF_DEV_NAME }}" ./arm-output

      - name: ğŸ“ Upload ARM template artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: adf-arm-template
          path: ./arm-output
